blank_issues_enabled: false
contact_links:
  - name: Priiiiyo Mirrorbot Channels
    url: https://t.me/PriiiiyoMirrorUpdates
    about: Updates Channels
  - name: Priiiiyo Mirrorbot Group
    url: https://t.me/PriiiiyoSupport
    about: Support Group
